#!/usr/bin/python3

def raise_exception():
    n = "t"
    print(5 + n)
